// <auto-generated />
using System;
using Domain.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiColegio.Migrations
{
    [DbContext(typeof(ConexionSQLServer))]
    [Migration("20221229223848_First_Migration")]
    partial class First_Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ApiColegio.Models.Course", b =>
                {
                    b.Property<int>("IdCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_curso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCourse"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("seccion")
                        .IsFixedLength();

                    b.HasKey("IdCourse");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("ApiColegio.Models.Grade", b =>
                {
                    b.Property<int>("IdStudent")
                        .HasColumnType("int")
                        .HasColumnName("id_estudiante");

                    b.Property<int>("IdSubject")
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    b.Property<int>("FirstPartial")
                        .HasColumnType("int")
                        .HasColumnName("calificacion");

                    b.HasKey("IdStudent", "IdSubject")
                        .HasName("PK_Grades");

                    b.HasIndex("IdSubject");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("ApiColegio.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estudiante");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStudent"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("IdCourse")
                        .HasColumnType("int")
                        .HasColumnName("id_curso");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasColumnName("telefono")
                        .IsFixedLength();

                    b.Property<string>("Tutor")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tutor");

                    b.HasKey("IdStudent");

                    b.HasIndex("IdCourse");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("ApiColegio.Models.Subject", b =>
                {
                    b.Property<int>("IdSubject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSubject"), 1L, 1);

                    b.Property<int>("IdCourse")
                        .HasColumnType("int")
                        .HasColumnName("id_curso");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasColumnName("nombre_corto")
                        .IsFixedLength();

                    b.HasKey("IdSubject");

                    b.HasIndex("IdCourse");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("ApiColegio.Models.Teacher", b =>
                {
                    b.Property<int>("IdTeacher")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_profesor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTeacher"), 1L, 1);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nombre");

                    b.Property<int>("IdSubject")
                        .HasColumnType("int")
                        .HasColumnName("id_materia");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .HasColumnName("telefono")
                        .IsFixedLength();

                    b.HasKey("IdTeacher");

                    b.HasIndex(new[] { "IdSubject" }, "IX_Profesores")
                        .IsUnique();

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("ApiColegio.Models.Grade", b =>
                {
                    b.HasOne("ApiColegio.Models.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("IdStudent")
                        .IsRequired()
                        .HasConstraintName("FK_Grades_Students");

                    b.HasOne("ApiColegio.Models.Subject", "Subject")
                        .WithMany("Grades")
                        .HasForeignKey("IdSubject")
                        .IsRequired()
                        .HasConstraintName("FK_Grades_Subjects");

                    b.Navigation("Student");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ApiColegio.Models.Student", b =>
                {
                    b.HasOne("ApiColegio.Models.Course", "Course")
                        .WithMany("Students")
                        .HasForeignKey("IdCourse")
                        .IsRequired()
                        .HasConstraintName("FK_Estudiantes_Cursos");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ApiColegio.Models.Subject", b =>
                {
                    b.HasOne("ApiColegio.Models.Course", "Course")
                        .WithMany("Subjects")
                        .HasForeignKey("IdCourse")
                        .IsRequired()
                        .HasConstraintName("FK_Materias_Cursos");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("ApiColegio.Models.Teacher", b =>
                {
                    b.HasOne("ApiColegio.Models.Subject", "Subject")
                        .WithOne("Teacher")
                        .HasForeignKey("ApiColegio.Models.Teacher", "IdSubject")
                        .IsRequired()
                        .HasConstraintName("FK_Profesores_Materias");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ApiColegio.Models.Course", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("ApiColegio.Models.Student", b =>
                {
                    b.Navigation("Grades");
                });

            modelBuilder.Entity("ApiColegio.Models.Subject", b =>
                {
                    b.Navigation("Grades");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
